import { Inter } from "next/font/google";
import "./globals.css";
import Page from "./component/header/page";
import Navbar from "./component/Navbar/navbar";
import Footer from "./component/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Page/>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
